package com.spotinst.sdkjava.model.responses.elastigroup.aws;

import com.spotinst.sdkjava.client.response.BaseServiceItemsResponse;
import com.spotinst.sdkjava.model.api.elastigroup.aws.ApiElastigroupTerminateStatefulInstanceImportResponse;

public class ElastigroupTerminateStatefulInstanceImportApiResponse extends BaseServiceItemsResponse<ApiElastigroupTerminateStatefulInstanceImportResponse> {
}